// A fixed scripted playthrough shared by the smoke suite (Node) and the boot
// page (browser). Both environments must produce the identical fingerprint.
// The script exercises every verb and completes the whole chapter. Over-
// issued attacks past a kill are safe (`already_down`, never a throw), so
// combat loops carry generous margins and stay robust across any seed.
//
// Deliberately sparing with TICK: enemy/car movement only happens on TICK
// (src/sim/reduce.js), so a script that rarely ticks keeps every entity
// effectively parked at its spawn/home position between scripted actions —
// exactly like the two earlier games' demos, which also never had to account
// for enemies repositioning mid-script. The AI/pathfinding/car systems
// themselves get dedicated, focused smoke tests instead (see scripts/
// smoke.mjs) rather than being exercised incidentally here.
//
// Movement is generated by a path stepper that always routes via Main Street
// (y=10, open for its full width) as a safe "gap row" — every waypoint used
// below sits on a column that is fully open outside y=10 too, so the L-path
// (vertical at the current column -> horizontal along y=10 -> vertical at
// the target column) never clips a building.

export const DEMO_SEED = 0xc17a3; // "city"

const sign = (n) => (n > 0 ? 1 : n < 0 ? -1 : 0);

export function demoCommands() {
  const cmds = [];
  const cur = { x: 1, y: 10 }; // spawn
  const M = (dx, dy) => cmds.push({ type: 'MOVE', dx, dy });
  const walkToRaw = (tx, ty) => {
    while (cur.x !== tx || cur.y !== ty) {
      const dx = sign(tx - cur.x), dy = sign(ty - cur.y);
      M(dx, dy);
      cur.x += dx; cur.y += dy;
    }
  };
  const walkTo = (tx, ty) => {
    walkToRaw(cur.x, 10);
    walkToRaw(tx, 10);
    walkToRaw(tx, ty);
  };
  const charge = (n) => { cmds.push({ type: 'CHARGE', start: true }); for (let i = 1; i < n; i++) cmds.push({ type: 'CHARGE' }); };

  cmds.push({ type: 'TICK' });

  // --- Quest 1: City of Rules -------------------------------------------
  walkTo(3, 10);
  cmds.push({ type: 'TALK', npcId: 'ferro' }); // offers 'city-of-rules'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'city-of-rules' });
  walkTo(20, 10); // the training-yard zone, at Ossa's post — completes quest 1

  // --- Quest 2: Read the City (kill a Sentry — no immunity) ---------------
  // Every quest routes through Ferro (see content.js) — Ossa is shop-only.
  walkTo(3, 10);
  cmds.push({ type: 'TALK', npcId: 'ferro' }); // offers 'read-the-city'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'read-the-city' });
  walkTo(7, 4);
  for (let i = 0; i < 5; i++) cmds.push({ type: 'MELEE', enemyId: 'sentry1' });

  // --- Quest 3: Watch Them Move (kill a Cutthroat — immune: melee) --------
  walkTo(3, 10);
  cmds.push({ type: 'TALK', npcId: 'ferro' }); // offers 'watch-them-move'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'watch-them-move' });
  walkTo(21, 15);
  cmds.push({ type: 'MELEE', enemyId: 'cutthroat1' }); // no_effect (immune: melee)
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'cutthroat1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'cutthroat1' });
  charge(6);
  cmds.push({ type: 'AURA_BLAST', enemyId: 'cutthroat1' });
  cmds.push({ type: 'AURA_BLAST', enemyId: 'cutthroat1' });

  // --- Quest 4: Ferro's Ledger (collect the signet) -----------------------
  walkTo(3, 10);
  cmds.push({ type: 'TALK', npcId: 'ferro' }); // offers 'ferros-ledger'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'ferros-ledger' });
  walkTo(6, 3);
  cmds.push({ type: 'INTERACT', pickupId: 'signet1' });

  // --- Quest 5: The Warden's Seal (finale) --------------------------------
  walkTo(3, 10);
  cmds.push({ type: 'TALK', npcId: 'ferro' }); // offers 'the-wardens-seal'
  cmds.push({ type: 'ACCEPT_QUEST', questId: 'the-wardens-seal' });

  walkTo(21, 14);
  for (let i = 0; i < 5; i++) cmds.push({ type: 'MELEE', enemyId: 'bulwark-elite1' }); // immune: aura, melee works

  walkTo(30, 15);
  cmds.push({ type: 'INTERACT', pickupId: 'seal1' });

  // Reach the arena — the last objective. The Warden rises.
  walkTo(29, 10);

  // Face the Warden.
  walkTo(29, 10);
  for (let cyc = 0; cyc < 8; cyc++) {
    charge(6);
    cmds.push({ type: 'AURA_BLAST', enemyId: 'warden1' });
    cmds.push({ type: 'AURA_BLAST', enemyId: 'warden1' });
    cmds.push({ type: 'MELEE', enemyId: 'warden1' });
    cmds.push({ type: 'MELEE', enemyId: 'warden1' });
    if (cyc === 1) cmds.push({ type: 'ENEMY_STRIKE', enemyId: 'warden1' });
  }

  cmds.push({ type: 'CHOOSE_FATE', fate: 'depose' });
  walkTo(31, 10);
  cmds.push({ type: 'TICK' });
  cmds.push({ type: 'TICK' });

  return cmds;
}
